services:
  fastapi-app:
    build: ./backend
    container_name: fastapi-store-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: uvicorn backend.app:app --host 0.0.0.0 --reload

  frontend:
    build: ./frontend
    container_name: vite-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0

volumes:
  frontend_node_modules:
